version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "=== Installing dependencies for index-photos ==="
      - cd index-photos
      - if [ -f requirements.txt ]; then python -m pip install -r requirements.txt -t .; fi
      - cd ..
      - echo "=== Installing dependencies for search-photos ==="
      - cd search-photos
      - if [ -f requirements.txt ]; then python -m pip install -r requirements.txt -t .; fi
      - cd ..
  build:
    commands:
      - echo "=== Zipping index-photos ==="
      - cd index-photos
      - zip -r ../index-photos.zip .
      - cd ..
      - echo "=== Zipping search-photos ==="
      - cd search-photos
      - zip -r ../search-photos.zip .
      - cd ..
artifacts:
  files:
    - index-photos.zip
    - search-photos.zip
